"""Contract tests for user CRUD endpoints.

These tests verify that the API responses match the expected schemas
for user management endpoints (POST, PATCH, DELETE /api/v1/users).
"""
import pytest
from pydantic import ValidationError
from uuid import UUID

from app.models.user import (
    UserCreate,
    UserRead,
    UserUpdate,
    UserReadWithTempPassword,
    UserRole,
)


class TestCreateUserContract:
    """Contract tests for POST /api/v1/users endpoint."""

    def test_create_user_request_contract(self):
        """Verify create user request matches UserCreateRequest schema."""
        request_data = {
            "name": "John Doe",
            "email": "john@example.com",
            "role": "member",
            "is_project_manager": False,
        }

        # The request uses a simplified schema without password
        # (password is auto-generated by the backend)
        from app.api.endpoints.users import UserCreateRequest
        request = UserCreateRequest(**request_data)

        assert request.name == "John Doe"
        assert request.email == "john@example.com"
        assert request.role.value == "member"
        assert request.is_project_manager is False

    def test_create_user_request_invalid_email(self):
        """Verify create user rejects invalid email."""
        from app.api.endpoints.users import UserCreateRequest

        with pytest.raises(ValidationError):
            UserCreateRequest(
                name="John Doe",
                email="not-an-email",
                role="member",
            )

    def test_create_user_response_contract(self):
        """Verify create user response matches UserReadWithTempPassword schema."""
        response_data = {
            "id": "123e4567-e89b-12d3-a456-426614174000",
            "email": "john@example.com",
            "name": "John Doe",
            "role": "member",
            "agency_id": "123e4567-e89b-12d3-a456-426614174000",
            "created_at": "2025-01-29T12:00:00",
            "updated_at": None,
            "temp_password": "Temp@12345678",  # 12-char temporary password
        }

        # Should validate successfully
        user_response = UserReadWithTempPassword(**response_data)

        assert str(user_response.id) == "123e4567-e89b-12d3-a456-426614174000"
        assert user_response.email == "john@example.com"
        assert user_response.name == "John Doe"
        assert user_response.role.value == "member"
        assert user_response.temp_password == "Temp@12345678"

    def test_create_user_response_with_admin_role(self):
        """Verify create user response with admin role."""
        response_data = {
            "id": "123e4567-e89b-12d3-a456-426614174001",
            "email": "admin@example.com",
            "name": "Admin User",
            "role": "admin",
            "agency_id": "123e4567-e89b-12d3-a456-426614174000",
            "created_at": "2025-01-29T12:00:00",
            "updated_at": None,
            "temp_password": "Admin@12345",
        }

        user_response = UserReadWithTempPassword(**response_data)

        assert user_response.role.value == "admin"
        assert user_response.temp_password == "Admin@12345"


class TestUpdateUserContract:
    """Contract tests for PATCH /api/v1/users/{id} endpoint."""

    def test_update_user_request_contract(self):
        """Verify update user request matches UserUpdateRequest schema."""
        request_data = {
            "name": "Jane Doe",
            "email": "jane@example.com",
            "role": "admin",
            "is_project_manager": True,
        }

        from app.api.endpoints.users import UserUpdateRequest
        request = UserUpdateRequest(**request_data)

        assert request.name == "Jane Doe"
        assert request.email == "jane@example.com"
        assert request.role.value == "admin"
        assert request.is_project_manager is True

    def test_update_user_partial_request_contract(self):
        """Verify update user accepts partial data."""
        request_data = {
            "name": "Jane Doe",
        }

        from app.api.endpoints.users import UserUpdateRequest
        request = UserUpdateRequest(**request_data)

        assert request.name == "Jane Doe"
        # Other fields should be optional/None
        assert request.email is None
        assert request.role is None

    def test_update_user_response_contract(self):
        """Verify update user response matches UserRead schema."""
        response_data = {
            "id": "123e4567-e89b-12d3-a456-426614174000",
            "email": "jane@example.com",
            "name": "Jane Doe",
            "role": "admin",
            "agency_id": "123e4567-e89b-12d3-a456-426614174000",
            "created_at": "2025-01-29T12:00:00",
            "updated_at": "2025-01-30T14:30:00",
        }

        # Should validate successfully
        user = UserRead(**response_data)

        assert str(user.id) == "123e4567-e89b-12d3-a456-426614174000"
        assert user.email == "jane@example.com"
        assert user.name == "Jane Doe"
        assert user.role.value == "admin"


class TestDeleteUserContract:
    """Contract tests for DELETE /api/v1/users/{id} endpoint."""

    def test_delete_user_response_contract(self):
        """Verify delete user returns 204 No Content."""
        # DELETE endpoint returns 204 No Content with no body
        # This test validates the contract specification
        assert True  # No response body to validate for 204

    def test_delete_user_id_parameter_contract(self):
        """Verify user ID parameter is a valid UUID."""
        user_id = "123e4567-e89b-12d3-a456-426614174000"

        # Should validate as UUID
        uuid = UUID(user_id)
        assert str(uuid) == user_id

    def test_delete_user_invalid_id_format(self):
        """Verify delete user rejects invalid UUID format."""
        with pytest.raises(ValueError):
            UUID("not-a-valid-uuid")
