apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "teamflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "teamflow.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "teamflow.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.backend.service.targetPort }}
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: teamflow-secrets
              key: DATABASE_URL
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: teamflow-secrets
              key: OPENAI_API_KEY
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: teamflow-secrets
              key: SECRET_KEY
        - name: BETTER_AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: teamflow-secrets
              key: BETTER_AUTH_SECRET
        - name: FRONTEND_URL
          value: "http://localhost:3000,http://127.0.0.1:39315,http://192.168.49.2"
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: teamflow-secrets
              key: GEMINI_API_KEY
              optional: true
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: teamflow-secrets
              key: OPENROUTER_API_KEY
              optional: true
        - name: QDRANT_URL
          value: "http://qdrant.teamflow.svc.cluster.local:6333"
        - name: QDRANT_API_KEY
          valueFrom:
            secretKeyRef:
              name: teamflow-secrets
              key: QDRANT_API_KEY
              optional: true
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.backend.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.backend.readinessProbe | nindent 10 }}
