apiVersion: v1
kind: ConfigMap
metadata:
  name: teamflow-config
  namespace: {{ .Values.namespace }}
data:
  NEXT_PUBLIC_API_URL: {{ .Values.frontend.env.NEXT_PUBLIC_API_URL | quote }}
  BACKEND_URL: {{ .Values.frontend.env.BACKEND_URL | quote }}
